apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ohtu-faded-parsons
  namespace: timed-parsons
spec:
  lookupPolicy:
    local: false
  tags:
    - name: staging
      from:
        kind: DockerImage
        name: quay.io/tike/ohtu-faded-parsons:staging
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
