apiVersion: v1
kind: Service
metadata:
  name: faded-parsons-staging
  namespace: timed-parsons
  labels:
    app: faded-parsons-staging

spec:
  selector:
    app: faded-parsons-staging

  ports:
    - name: http
      port: 8080
      targetPort: 8080
