FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["pytest", "--cov=backend", "--cov-report=html", "--cov-report=term-missing"]
