FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

COPY . .

CMD ["pytest", "-n", "auto", "--dist=loadscope", "--cov=backend", "--cov-report=html", "--cov-report=term-missing"]
