FROM mcr.microsoft.com/playwright:v1.59.0-noble
WORKDIR /usr/src/app

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm npm ci --no-audit --no-fund

COPY . .

CMD ["npx", "playwright", "test"]
