apiVersion: apps/v1
kind: Deployment
metadata:
  name: faded-parsons-production
  namespace: timed-parsons
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"ohtu-faded-parsons:production","namespace":"timed-parsons"},"fieldPath":"spec.template.spec.containers[?(@.name==\"faded-parsons-production\")].image"}]
  labels:
    app: faded-parsons-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faded-parsons-production
  template:
    metadata:
      labels:
        app: faded-parsons-production
    spec:
      containers:
        - name: faded-parsons-production
          image: quay.io/tike/ohtu-faded-parsons:production
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - alembic upgrade head && exec uvicorn backend.main:app --host 0.0.0.0 --port 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: DATABASE_URL
            - name: AUTO_INIT_DB
              value: "false"
            - name: RUN_SEED_ON_STARTUP # Not needed in production, only for staging
              value: "false"
            - name: TEACHER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: teachertoken
                  key: TEACHER_REGISTRATION_TOKEN
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: ALLOWED_ORIGINS
              value: "https://faded-parsons-production-timed-parsons.ext.ocp-prod-0.k8s.it.helsinki.fi,https://parsonscodelab.web.helsinki.fi"
            - name: COOKIE_SECURE
              value: "true"
          envFrom:
            - secretRef:
                name: saml-config-production
                optional: true
          volumeMounts:
            - name: saml-certificates
              mountPath: /etc/saml
              readOnly: true
            - name: saml-idp-certificate
              mountPath: /etc/saml/idp
              readOnly: true
          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /
              port: 8000

          livenessProbe:
            httpGet:
              path: /
              port: 8000
      volumes:
        - name: saml-certificates
          secret:
            secretName: cert-and-private-key
            items:
              - key: shib.crt
                path: sp.crt
              - key: shib.key
                path: sp.key
        - name: saml-idp-certificate
          secret:
            secretName: saml-idp-certificate-production
            optional: true
