name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Login to Quay # Try to login with the token an username in github actions secretss || using --password-stdin so that the password is not reaveled in the console
        run: |
          echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image # Build and name the image staging
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.staging
          push: true
          tags: quay.io/tike/ohtu-faded-parsons:staging
          cache-from: type=gha,scope=staging
          cache-to: type=gha,mode=max,scope=staging

      - name: Build Shibboleth proxy image
        uses: docker/build-push-action@v6
        with:
          context: apache
          file: apache/Dockerfile
          push: true
          tags: quay.io/tike/ohtu-faded-parsons-shibboleth:staging
          cache-from: type=gha,scope=staging-shibboleth
          cache-to: type=gha,mode=max,scope=staging-shibboleth
